import: rubensworks/travis-presets:node-base.yml@master
install: yarn install --ignore-scripts
script:
- yarn run lint
- yarn run build
dist: trusty

cache:
  yarn: true
  directories:
  - node_modules
before_deploy:
  - rm .gitignore
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master
    node_js: "node"
